project:
  type: website

format:
  html:
    theme: yeti
execute:
  freeze: auto
# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "geotypes"
  description: "A python library making it easier for working with geospatial data."
#  url: "https://jacksonhshields.github.io/situ/"
  page-navigation: true

  navbar:
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/jacksonhshields/geotypes
          - text: Report a bug
            url: https://github.com/jacksonhshields/geotypes/new?assignees=&labels=bug&projects=&template=bug-report.yml&title=bug
          - text: Report a documentation issue
            url: https://github.com/jacksonhshields/geotypes/new?assignees=&labels=docs&projects=&template=docs-issue.yml&title=docs
          - text: Submit a feature request
            url: https://github.com/jacksonhshields/geotypes/new?assignees=&labels=feature&projects=&template=feature-request.yml&title=feat
          - text: Ask the community for help
            url: https://github.com/jacksonhshields/geotypes/discussions/new?category=q-a

    left:
      - sidebar:getting-started
      - sidebar:tutorials
      - sidebar:reference

  sidebar:
    - id: getting-started
      title: "Getting Started"
      style: "docked"
      collapse-level: 2
      contents:
        - get_started.qmd
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      collapse-level: 2
      contents:
          - tutorials/DataTypes.ipynb
          # - tutorials/Rasters.ipynb
    - id: reference
      title: "Reference"
      style: "docked"
      collapse-level: 2
      contents:
          - reference/index.qmd
          - auto: reference/*.qmd


quartodoc:
  parser: google
  # the name used to import the package you want to create reference docs for
  package: geotypes
  title: Reference
  # write sidebar data to this file
  sidebar: reference/_sidebar.yml
  render_interlinks: true

  sections:
    - title: Geometry
      desc: Geometry
      contents:
        - geometry
    - title: Rasters
      desc: Rasters
      contents:
        - rasters
    - title: Features
      desc: Features
      contents:
        - features